---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sbballro/public_html
    - /bin/cp _.sbballroomdance.com.pem.txt $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R actions $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
